{% set name = "LbAPCommon" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbAPCommon-{{ version }}.tar.gz
  sha256: a6dbd92cb6460afe5cf7e54572dcaa029dc0f4420c2fc50749265383839a8249

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - jinja2
    - lxml
    - python >=3.6
    - pyyaml
    - strictyaml
    - requests
    - requests-kerberos
    - uproot >=4.0.0
    - awkward >=1.0.0
    - boost-histogram
    - hist
    - xrootd

test:
  imports:
    - LbAPCommon
    - LbAPCommon.cern_sso
    - LbAPCommon.linting
    - LbAPCommon.validators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/LbAPCommon
  summary: Common utilities used by LHCb DPA WP2 related software
  dev_url: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/LbAPCommon
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
