{% set name = "lbapcommon" %}
{% set version = "0.5.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbAPCommon-{{ version }}.tar.gz
  sha256: 8861f5d277f320d5afe00339ae28be5df9c7e8751e24fd2a4f09de9c1a746d8a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - awkward >=1.0.0
    - boost-histogram
    - hist
    - jinja2
    - lxml
    - matplotlib-base
    - python >=3.6
    - pyyaml
    - requests
    - requests-kerberos
    - setuptools
    - strictyaml
    - uproot >=4.0.0
    - xrootd

test:
  imports:
    - LbAPCommon
    - LbAPCommon.cern_sso
    - LbAPCommon.linting
    - LbAPCommon.validators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/LbAPCommon
  summary: Common utilities used by LHCb DPA WP2 related software
  dev_url: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/LbAPCommon
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AidanWiederhold
    - chrisburr
