{% set name = "LbAPCommon" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbAPCommon-{{ version }}.tar.gz
  sha256: 1076c523f9f2ccd5dcaf41b35c5c52315e7b22aa3b02ff1843b1a4c163d4dd8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - jinja2
    - lxml
    - python >=3.6
    - pyyaml
    - strictyaml
    - requests
    - requests-kerberos

test:
  imports:
    - LbAPCommon
    - LbAPCommon.cern_sso
    - LbAPCommon.linting
    - LbAPCommon.validators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/LbAPCommon
  summary: Common utilities used by LHCb DPA WP2 related software
  dev_url: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/LbAPCommon
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
